// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDhPAUxTyntdnrr6Ni74-P45VTSV7ODaM',
    appId: '1:340678158393:web:368f9410d7f78ec860c5e8',
    messagingSenderId: '340678158393',
    projectId: 'plante-app-fde8e',
    authDomain: 'plante-app-fde8e.firebaseapp.com',
    storageBucket: 'plante-app-fde8e.firebasestorage.app',
    measurementId: 'G-H4YDZBD8H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9JXisX9ja2t3g0ZDp5K-uQY27-dyOpuk',
    appId: '1:340678158393:android:ae7b9e28d5ae696d60c5e8',
    messagingSenderId: '340678158393',
    projectId: 'plante-app-fde8e',
    storageBucket: 'plante-app-fde8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeZoLGyFSE10T4wSZMW3C5D2WAmyoeugo',
    appId: '1:340678158393:ios:bc959445a367d35c60c5e8',
    messagingSenderId: '340678158393',
    projectId: 'plante-app-fde8e',
    storageBucket: 'plante-app-fde8e.firebasestorage.app',
    iosBundleId: 'com.example.plante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeZoLGyFSE10T4wSZMW3C5D2WAmyoeugo',
    appId: '1:340678158393:ios:bc959445a367d35c60c5e8',
    messagingSenderId: '340678158393',
    projectId: 'plante-app-fde8e',
    storageBucket: 'plante-app-fde8e.firebasestorage.app',
    iosBundleId: 'com.example.plante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDhPAUxTyntdnrr6Ni74-P45VTSV7ODaM',
    appId: '1:340678158393:web:f356802534c1952560c5e8',
    messagingSenderId: '340678158393',
    projectId: 'plante-app-fde8e',
    authDomain: 'plante-app-fde8e.firebaseapp.com',
    storageBucket: 'plante-app-fde8e.firebasestorage.app',
    measurementId: 'G-2WQXQPV430',
  );
}
